# Using version 2 as required by the latest GoReleaser
version: 2
project_name: go-builder-kit

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/builder-gen/main.go
    binary: builder-gen
  - id: library
    skip: true  # Skip binary builds for the library part

# Archives configuration
archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # Using the new format configuration as per https://goreleaser.com/deprecations/#archivesformat
    formats: [ 'tar.gz' ]
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]

checksum:
  name_template: 'checksums.txt'

# Snapshot configuration
# As per https://goreleaser.com/deprecations/#snapshotname_template
snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: adil-faiyaz98
    name: go-builder-kit
  prerelease: auto
  draft: false
  name_template: "{{ .ProjectName }} v{{ .Version }}"
  header: |
    # {{ .ProjectName }} v{{ .Version }}

    This release includes improvements to the builder pattern implementation, enhanced nested struct support, and bug fixes.

  footer: |
    ## Installation

    ```bash
    go get github.com/adil-faiyaz98/go-builder-kit@{{ .Tag }}
    ```

    ## Documentation

    Full documentation is available at [pkg.go.dev](https://pkg.go.dev/github.com/adil-faiyaz98/go-builder-kit@{{ .Tag }})

    ## Thanks

    Thanks to all contributors who made this release possible!

announce:
  skip: false
