name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # THIS LINE IS IMPORTANT

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Update Go pkg.go.dev
        run: |
          # Trigger pkg.go.dev to update
          GOPROXY=https://proxy.golang.org go list -m github.com/adil-faiyaz98/go-builder-kit@${{ github.ref_name }}
          # Allow some time for the proxy to update
          sleep 10
          # Verify the module is available
          go list -m github.com/adil-faiyaz98/go-builder-kit@${{ github.ref_name }} || echo "Module may not be immediately available, but the update request has been sent."
