name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install GoReleaser Nightly and add to PATH
        run: |
          curl -sL https://github.com/goreleaser/goreleaser/releases/download/nightly/goreleaser_Linux_x86_64.tar.gz -o goreleaser.tar.gz
          tar -xzf goreleaser.tar.gz
          chmod +x goreleaser
          mkdir -p $HOME/bin
          mv goreleaser $HOME/bin/goreleaser
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Confirm GoReleaser version
        run: goreleaser --version

      - name: Run GoReleaser
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
