name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install GoReleaser Nightly and add to PATH
        run: |
          curl -sL https://github.com/goreleaser/goreleaser/releases/download/nightly/goreleaser_Linux_x86_64.tar.gz -o goreleaser.tar.gz
          tar -xzf goreleaser.tar.gz
          chmod +x goreleaser
          mkdir -p $HOME/bin
          mv goreleaser $HOME/bin/goreleaser
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Confirm GoReleaser version
        run: goreleaser --version

      - name: Run GoReleaser Snapshot
        run: goreleaser release --snapshot --clean
