name: Simple CI/CD

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"
          cache: true

      - name: Run tests
        run: go test ./models/... ./builders/... ./pkg/builder/... ./tests/...
        # Exclude cmd directory from tests

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"
          cache: true

      - name: Build
        run: go build -v ./models/... ./builders/... ./pkg/builder/...
        # Exclude cmd directory from build

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"
          cache: true

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create a release using the GitHub CLI
          gh release create ${{ github.ref_name }} \
            --title "${{ github.ref_name }}" \
            --generate-notes

      - name: Update Go pkg.go.dev
        run: |
          # Trigger pkg.go.dev to update
          GOPROXY=https://proxy.golang.org go list -m github.com/adil-faiyaz98/go-builder-kit@${{ github.ref_name }}
          # Allow some time for the proxy to update
          sleep 10
          # Verify the module is available
          go list -m github.com/adil-faiyaz98/go-builder-kit@${{ github.ref_name }} || echo "Module may not be immediately available, but the update request has been sent."
